`timescale 1ns / 1ps
module cosim_top;
    // Auto-generated by gen_cosim_top.py from tb_sar_adc.spectre.
    // Instance paths were discovered automatically by searching the netlist for each --modules name.
    // Defaults below are placeholders -- check against the real supply domain before trusting them.
    localparam VTH_LO = 0.6;
    localparam VTH_HI = 1.2;
    localparam D2A_VDD = 1.8;
    localparam D2A_R   = 1e3;
    localparam D2A_C   = 1e-12;

    // adc at x2:A2
    reg adc__x2_A2__Clk;
    reg adc__x2_A2__Comp;
    reg adc__x2_A2__Start;
    wire adc__x2_A2__Sample;
    wire adc__x2_A2__Done;
    wire [5:0] adc__x2_A2__Result;

    adc u_adc__x2_A2 (
        .Clk(adc__x2_A2__Clk),
        .Comp(adc__x2_A2__Comp),
        .Start(adc__x2_A2__Start),
        .Sample(adc__x2_A2__Sample),
        .Done(adc__x2_A2__Done),
        .Result(adc__x2_A2__Result)
    );

    initial begin
        $dumpfile("cosim.vcd"); $dumpvars(0, cosim_top);

        // adc at x2:A2
        $cosim_a2d("CLK", adc__x2_A2__Clk, VTH_LO, VTH_HI);
        $cosim_a2d("x2:COMP", adc__x2_A2__Comp, VTH_LO, VTH_HI);
        $cosim_a2d("START", adc__x2_A2__Start, VTH_LO, VTH_HI);
        $cosim_d2a("x2:SAMPLE", adc__x2_A2__Sample, D2A_VDD, D2A_R, D2A_C);
        $cosim_d2a("VALID", adc__x2_A2__Done, D2A_VDD, D2A_R, D2A_C);
        $cosim_d2a("D[5]", adc__x2_A2__Result[5], D2A_VDD, D2A_R, D2A_C);
        $cosim_d2a("D[4]", adc__x2_A2__Result[4], D2A_VDD, D2A_R, D2A_C);
        $cosim_d2a("D[3]", adc__x2_A2__Result[3], D2A_VDD, D2A_R, D2A_C);
        $cosim_d2a("D[2]", adc__x2_A2__Result[2], D2A_VDD, D2A_R, D2A_C);
        $cosim_d2a("D[1]", adc__x2_A2__Result[1], D2A_VDD, D2A_R, D2A_C);
        $cosim_d2a("D[0]", adc__x2_A2__Result[0], D2A_VDD, D2A_R, D2A_C);

        $cosim_run("tb_sar_adc.spectre", 0.00025, 1e-08);
    end
endmodule
