[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "pyvacask"
version = "0.1.0"

[project.optional-dependencies]
dev = [
    "pytest",
    "numpy",
    "matplotlib"
]

[tool.pytest.ini_options]
addopts = ""
testpaths = [
    "tests",
]
