`timescale 1ns / 1ps
module cosim_top;
    // Auto-generated by gen_cosim_top.py from tb_sar_adc.spectre.
    // Instance paths were discovered automatically by searching the netlist for each --modules name.
    // Defaults below are placeholders -- check against the real supply domain before trusting them.
    localparam VTH_LO = 0.6;
    localparam VTH_HI = 1.2;
    localparam D2A_VDD = 1.8;
    localparam D2A_R   = 1e3;
    localparam D2A_C   = 1e-12;

    // adc at x1:x8
    reg adc__x1_x8__Clk;
    reg adc__x1_x8__Comp;
    reg adc__x1_x8__Start;
    wire adc__x1_x8__Sample;
    wire adc__x1_x8__Done;
    wire [5:0] adc__x1_x8__Result;

    adc u_adc__x1_x8 (
        .Clk(adc__x1_x8__Clk),
        .Comp(adc__x1_x8__Comp),
        .Start(adc__x1_x8__Start),
        .Sample(adc__x1_x8__Sample),
        .Done(adc__x1_x8__Done),
        .Result(adc__x1_x8__Result)
    );

    initial begin
        $dumpfile("cosim.vcd"); $dumpvars(0, cosim_top);

        // adc at x1:x8
        $cosim_a2d("CLK", adc__x1_x8__Clk, VTH_LO, VTH_HI);
        $cosim_a2d("x1:COMP", adc__x1_x8__Comp, VTH_LO, VTH_HI);
        $cosim_a2d("START", adc__x1_x8__Start, VTH_LO, VTH_HI);
        $cosim_d2a("x1:SAMPLE", adc__x1_x8__Sample, D2A_VDD, D2A_R, D2A_C);
        $cosim_d2a("VALID", adc__x1_x8__Done, D2A_VDD, D2A_R, D2A_C);
        $cosim_d2a("D[5]", adc__x1_x8__Result[5], D2A_VDD, D2A_R, D2A_C);
        $cosim_d2a("D[4]", adc__x1_x8__Result[4], D2A_VDD, D2A_R, D2A_C);
        $cosim_d2a("D[3]", adc__x1_x8__Result[3], D2A_VDD, D2A_R, D2A_C);
        $cosim_d2a("D[2]", adc__x1_x8__Result[2], D2A_VDD, D2A_R, D2A_C);
        $cosim_d2a("D[1]", adc__x1_x8__Result[1], D2A_VDD, D2A_R, D2A_C);
        $cosim_d2a("D[0]", adc__x1_x8__Result[0], D2A_VDD, D2A_R, D2A_C);

        $cosim_run("tb_sar_adc.spectre", 0.00025, 1e-08);
    end
endmodule
